param(
    [string]$WorkingDir = "",
    [string]$SecretDir = "",
    [string]$BackupDir = "",
    [string]$SecurityCenterDataDir = "",
    [string]$SecurityCenterStoreFile = "",
    [string]$SecurityCenterApiUrl = "http://127.0.0.1:8091",
    [string]$SecurityCenterWebUrl = "http://127.0.0.1:8092",
    [string]$SecurityCenterApiBase = "",
    [string]$AuthEnabled = "false",
    [string]$NoProxy = "*",
    [string]$PythonPath = "",
    [string]$PythonIoEncoding = "utf-8",
    [string]$EnvFile = "",
    [int[]]$Ports = @(8088, 18088, 8091, 8092),
    [switch]$SkipPortCleanup,
    [switch]$PersistUserEnvironment,
    [switch]$SkipUserEnvironmentPersist
)

$ErrorActionPreference = "Stop"

$RepoRoot = Split-Path -Parent $PSScriptRoot

function Write-Step {
    param([string]$Message)
    Write-Host "[showcase-reset] $Message" -ForegroundColor Cyan
}

function Resolve-OptionalPath {
    param(
        [string]$Candidate,
        [string]$Fallback
    )

    $value = $Candidate.Trim()
    if (-not $value) {
        $value = $Fallback
    }
    return [System.IO.Path]::GetFullPath($value)
}

function First-NonEmptyValue {
    param(
        [string]$Preferred,
        [string]$Fallback
    )

    if ($Preferred -and $Preferred.Trim()) {
        return $Preferred
    }
    return $Fallback
}

function Get-DefaultDemoRoot {
    $repoDriveRoot = [System.IO.Path]::GetPathRoot($RepoRoot)
    if (-not $repoDriveRoot) {
        $repoDriveRoot = [System.IO.Path]::GetPathRoot((Get-Location).Path)
    }
    return (Join-Path $repoDriveRoot "QwenPawDemo")
}

function ConvertTo-PowerShellSingleQuotedLiteral {
    param([string]$Value)

    return "'{0}'" -f ($Value -replace "'", "''")
}

function Set-ShowcaseEnvironmentVariable {
    param(
        [string]$Name,
        [string]$Value
    )

    Set-Item -Path ("Env:{0}" -f $Name) -Value $Value
    if ($shouldPersistUserEnvironment) {
        [Environment]::SetEnvironmentVariable($Name, $Value, "User")
    }
}

function Write-ShowcaseEnvironmentFile {
    param(
        [string]$Path,
        [hashtable]$Variables
    )

    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }

    $lines = @(
        "# Generated by scripts/reset-showcase-demo-state.ps1",
        "# Dot-source this file to load showcase environment variables into the current PowerShell session.",
        "# Example: . `"$Path`"",
        ""
    )

    foreach ($key in ($Variables.Keys | Sort-Object)) {
        $lines += ("`$env:{0} = {1}" -f $key, (ConvertTo-PowerShellSingleQuotedLiteral -Value ([string]$Variables[$key])))
    }

    Set-Content -LiteralPath $Path -Value $lines -Encoding UTF8
}

function Get-DefaultWorkingDir {
    $explicit = First-NonEmptyValue -Preferred $env:QWENPAW_WORKING_DIR -Fallback $env:COPAW_WORKING_DIR
    if ($explicit -and $explicit.Trim()) {
        return $explicit
    }

    return (Join-Path (Get-DefaultDemoRoot) "working2")
}

function Stop-ProcessesListeningOnPorts {
    param([int[]]$TargetPorts)

    foreach ($port in $TargetPorts) {
        $connections = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue |
            Select-Object -ExpandProperty OwningProcess -Unique
        foreach ($processId in $connections) {
            if (-not $processId -or $processId -eq 0) {
                continue
            }
            try {
                $process = Get-Process -Id $processId -ErrorAction Stop
                Write-Step "Stopping process $($process.ProcessName) ($processId) on port $port"
                Stop-Process -Id $processId -Force -ErrorAction Stop
            } catch {
                Write-Warning ([string]::Format("Failed to stop process {0} on port {1}: {2}", $processId, $port, $_.Exception.Message))
            }
        }
    }
}

function Reset-Directory {
    param([string]$Path)

    if (Test-Path -LiteralPath $Path) {
        Write-Step "Removing $Path"
        Remove-Item -LiteralPath $Path -Recurse -Force -ErrorAction Stop
    }
    Write-Step "Creating $Path"
    New-Item -ItemType Directory -Path $Path -Force | Out-Null
}

function Reset-FileParent {
    param([string]$Path)

    $parent = Split-Path -Parent $Path
    if (-not (Test-Path -LiteralPath $parent)) {
        New-Item -ItemType Directory -Path $parent -Force | Out-Null
    }
    if (Test-Path -LiteralPath $Path) {
        Write-Step "Removing $Path"
        Remove-Item -LiteralPath $Path -Force -ErrorAction Stop
    }
}

$workingFallback = Get-DefaultWorkingDir
$secretFallback = First-NonEmptyValue -Preferred $env:QWENPAW_SECRET_DIR -Fallback ("{0}.secret" -f $workingFallback)
$backupFallback = First-NonEmptyValue -Preferred $env:QWENPAW_BACKUP_DIR -Fallback ("{0}.backups" -f $workingFallback)
$securityCenterDataFallback = First-NonEmptyValue -Preferred $env:QWENPAW_SECURITY_CENTER_DATA_DIR -Fallback (Join-Path (Get-DefaultDemoRoot) "security-center-data")

$resolvedWorkingDir = Resolve-OptionalPath -Candidate $WorkingDir -Fallback $workingFallback
$resolvedSecretDir = Resolve-OptionalPath -Candidate $SecretDir -Fallback $secretFallback
$resolvedBackupDir = Resolve-OptionalPath -Candidate $BackupDir -Fallback $backupFallback
$resolvedSecurityCenterDataDir = $SecurityCenterDataDir.Trim()
if (-not $resolvedSecurityCenterDataDir) {
    $resolvedSecurityCenterDataDir = $securityCenterDataFallback
}
if ($resolvedSecurityCenterDataDir) {
    $resolvedSecurityCenterDataDir = [System.IO.Path]::GetFullPath($resolvedSecurityCenterDataDir)
}

$resolvedSecurityCenterStoreFile = $SecurityCenterStoreFile.Trim()
if (-not $resolvedSecurityCenterStoreFile) {
    $resolvedSecurityCenterStoreFile = Join-Path $RepoRoot "deploy\api\data\security-center-store.json"
}
$resolvedSecurityCenterStoreFile = [System.IO.Path]::GetFullPath($resolvedSecurityCenterStoreFile)

$resolvedSecurityCenterApiUrl = First-NonEmptyValue -Preferred $SecurityCenterApiUrl -Fallback (First-NonEmptyValue -Preferred $env:QWENPAW_SECURITY_CENTER_API_URL -Fallback "http://127.0.0.1:8091")
$resolvedSecurityCenterWebUrl = First-NonEmptyValue -Preferred $SecurityCenterWebUrl -Fallback (First-NonEmptyValue -Preferred $env:QWENPAW_SECURITY_CENTER_WEB_URL -Fallback "http://127.0.0.1:8092")
$resolvedSecurityCenterApiBase = First-NonEmptyValue -Preferred $SecurityCenterApiBase -Fallback (First-NonEmptyValue -Preferred $env:SECURITY_CENTER_API_BASE -Fallback $resolvedSecurityCenterApiUrl)
$resolvedAuthEnabled = First-NonEmptyValue -Preferred $AuthEnabled -Fallback (First-NonEmptyValue -Preferred $env:QWENPAW_AUTH_ENABLED -Fallback "false")
$resolvedNoProxy = First-NonEmptyValue -Preferred $NoProxy -Fallback (First-NonEmptyValue -Preferred $env:NO_PROXY -Fallback "*")
$resolvedPythonPath = First-NonEmptyValue -Preferred $PythonPath -Fallback (First-NonEmptyValue -Preferred $env:PYTHONPATH -Fallback (Join-Path $RepoRoot "src"))
$resolvedPythonIoEncoding = First-NonEmptyValue -Preferred $PythonIoEncoding -Fallback (First-NonEmptyValue -Preferred $env:PYTHONIOENCODING -Fallback "utf-8")
$resolvedEnvFile = $EnvFile.Trim()
if (-not $resolvedEnvFile) {
    $resolvedEnvFile = Join-Path (Get-DefaultDemoRoot) "showcase-demo-env.ps1"
}
$resolvedEnvFile = [System.IO.Path]::GetFullPath($resolvedEnvFile)

$showcaseEnvironment = [ordered]@{
    QWENPAW_WORKING_DIR = $resolvedWorkingDir
    QWENPAW_SECRET_DIR = $resolvedSecretDir
    QWENPAW_BACKUP_DIR = $resolvedBackupDir
    QWENPAW_SECURITY_CENTER_DATA_DIR = $resolvedSecurityCenterDataDir
    QWENPAW_SECURITY_CENTER_API_URL = $resolvedSecurityCenterApiUrl
    QWENPAW_SECURITY_CENTER_WEB_URL = $resolvedSecurityCenterWebUrl
    QWENPAW_AUTH_ENABLED = $resolvedAuthEnabled
    NO_PROXY = $resolvedNoProxy
    PYTHONPATH = $resolvedPythonPath
    PYTHONIOENCODING = $resolvedPythonIoEncoding
    SECURITY_CENTER_API_BASE = $resolvedSecurityCenterApiBase
}

$shouldPersistUserEnvironment = $PersistUserEnvironment -or -not $SkipUserEnvironmentPersist
$isDotSourced = $MyInvocation.InvocationName -eq "."

foreach ($entry in $showcaseEnvironment.GetEnumerator()) {
    Set-ShowcaseEnvironmentVariable -Name $entry.Key -Value ([string]$entry.Value)
}

Write-Step "Repo root: $RepoRoot"
Write-Step "WorkingDir: $resolvedWorkingDir"
Write-Step "SecretDir: $resolvedSecretDir"
Write-Step "BackupDir: $resolvedBackupDir"
if ($resolvedSecurityCenterDataDir) {
    Write-Step "SecurityCenterDataDir: $resolvedSecurityCenterDataDir"
}
Write-Step "SecurityCenterStoreFile: $resolvedSecurityCenterStoreFile"

if (-not $SkipPortCleanup) {
    Stop-ProcessesListeningOnPorts -TargetPorts $Ports
}

Reset-Directory -Path $resolvedWorkingDir
Reset-Directory -Path $resolvedSecretDir
Reset-Directory -Path $resolvedBackupDir

if ($resolvedSecurityCenterDataDir) {
    Reset-Directory -Path $resolvedSecurityCenterDataDir
}

Reset-FileParent -Path $resolvedSecurityCenterStoreFile

Write-ShowcaseEnvironmentFile -Path $resolvedEnvFile -Variables $showcaseEnvironment

Write-Step "Showcase demo state has been reset."
if ($isDotSourced) {
    Write-Step "Showcase environment variables have been applied to the current PowerShell terminal."
}
else {
    Write-Step "Showcase environment variables were applied inside this script invocation. Dot-source this script to keep them in the current terminal."
}
Write-Step "Environment loader written to: $resolvedEnvFile"
if ($shouldPersistUserEnvironment) {
    Write-Step "Showcase environment variables have also been persisted to the current User environment for new terminals."
}
else {
    Write-Step "User environment persistence was skipped."
}
Write-Host ""
Write-Host "One-step demo preparation is complete." -ForegroundColor Green
Write-Host "Recommended one-command current-terminal setup: . .\scripts\reset-showcase-demo-state.ps1"
if ($shouldPersistUserEnvironment) {
    Write-Host "You can also open a new terminal to inherit the persisted User environment."
}
else {
    Write-Host "User environment persistence is disabled for this run; keep using this terminal or load the generated env file elsewhere."
}
Write-Host "If needed, the generated loader can refresh another already-open terminal:"
Write-Host ('. "{0}"' -f $resolvedEnvFile)
Write-Host ""
Write-Host "Showcase environment variables:" -ForegroundColor Green
foreach ($entry in $showcaseEnvironment.GetEnumerator()) {
    Write-Host ('$env:{0} = "{1}"' -f $entry.Key, $entry.Value)
}